export interface StudentBadge {
  id: string;
  title: string;
  description: string;
  criteria: string;
  category: "milestone" | "streak" | "mastery" | "tutor" | "reward";
  tier: "bronze" | "silver" | "gold" | "diamond";
  icon: string;
  rewardGp: number;
  unlocked: boolean;
  unlockedAt?: string;
  progress: number; // 0 to 100
  currentValue: number;
  targetValue: number;
  unit: string;
}

export const initialBadges: StudentBadge[] = [
  {
    id: "first-lesson",
    title: "Bước Khởi Đầu",
    description: "Hoàn thành bài học lý thuyết đầu tiên trên nền tảng.",
    criteria: "Hoàn thành ít nhất 1 bài học bất kỳ",
    category: "milestone",
    tier: "bronze",
    icon: "emoji_events",
    rewardGp: 20,
    unlocked: true,
    unlockedAt: "2026-10-01",
    progress: 100,
    currentValue: 1,
    targetValue: 1,
    unit: "bài",
  },
  {
    id: "streak-3",
    title: "Kỷ Luật Vàng",
    description: "Duy trì thói quen học tập liên tục 3 ngày.",
    criteria: "Đăng nhập và học tập 3 ngày liên tiếp",
    category: "streak",
    tier: "silver",
    icon: "local_fire_department",
    rewardGp: 30,
    unlocked: true,
    unlockedAt: "2026-10-05",
    progress: 100,
    currentValue: 3,
    targetValue: 3,
    unit: "ngày",
  },
  {
    id: "self-solver",
    title: "Tự Giải Thần Tốc",
    description: "Hoàn thành xuất sắc bài tập theo từng bước tự giải.",
    criteria: "Giải đúng bài tập trong tính năng Tự giải",
    category: "mastery",
    tier: "silver",
    icon: "psychology",
    rewardGp: 25,
    unlocked: true,
    unlockedAt: "2026-10-06",
    progress: 100,
    currentValue: 1,
    targetValue: 1,
    unit: "bài",
  },
  {
    id: "gp-collector",
    title: "Triệu Phú GP",
    description: "Tích lũy đạt mốc 100 điểm thưởng GP học tập.",
    criteria: "Đạt tổng tích lũy từ 100 GP trở lên",
    category: "reward",
    tier: "gold",
    icon: "savings",
    rewardGp: 50,
    unlocked: true,
    unlockedAt: "2026-10-07",
    progress: 100,
    currentValue: 120,
    targetValue: 100,
    unit: "GP",
  },
  {
    id: "math-explorer",
    title: "Nhà Thám Hiểm Toán",
    description: "Nắm vững trọn vẹn chủ đề Căn thức bậc hai.",
    criteria: "Hoàn thành tất cả các bài học trong chủ đề Căn bậc hai",
    category: "mastery",
    tier: "gold",
    icon: "functions",
    rewardGp: 40,
    unlocked: true,
    unlockedAt: "2026-10-07",
    progress: 100,
    currentValue: 3,
    targetValue: 3,
    unit: "bài",
  },
  {
    id: "tutor-session",
    title: "Đồng Hành Cùng Tutor",
    description:
      "Tham gia buổi giải đáp và cố vấn học tập trực tiếp cùng Tutor.",
    criteria: "Hoàn thành 1 buổi học tương tác hoặc hỏi bài cùng Tutor",
    category: "tutor",
    tier: "gold",
    icon: "support_agent",
    rewardGp: 35,
    unlocked: true,
    unlockedAt: "2026-10-06",
    progress: 100,
    currentValue: 1,
    targetValue: 1,
    unit: "buổi",
  },
  {
    id: "exam-ace",
    title: "Chiến Binh Phòng Thi",
    description: "Hoàn thành bài thi thử với kết quả từ 8.5 điểm trở lên.",
    criteria: "Đạt từ 8.5 điểm trong phòng thi thử",
    category: "mastery",
    tier: "diamond",
    icon: "workspace_premium",
    rewardGp: 60,
    unlocked: false,
    progress: 80,
    currentValue: 7.2,
    targetValue: 8.5,
    unit: "điểm",
  },
  {
    id: "streak-7",
    title: "Kiên Trì Bất Tận",
    description: "Duy trì chuỗi học tập 7 ngày liên tiếp không ngắt quãng.",
    criteria: "Học tập liên tục 7 ngày",
    category: "streak",
    tier: "diamond",
    icon: "stars",
    rewardGp: 70,
    unlocked: false,
    progress: 57,
    currentValue: 4,
    targetValue: 7,
    unit: "ngày",
  },
  {
    id: "mastery-all",
    title: "Đỉnh Cao Tri Thức",
    description: "Hoàn thành 100% tất cả các bài học trong học kỳ.",
    criteria: "Đạt tỉ lệ hoàn thành 100% môn học",
    category: "milestone",
    tier: "diamond",
    icon: "military_tech",
    rewardGp: 100,
    unlocked: false,
    progress: 50,
    currentValue: 2,
    targetValue: 4,
    unit: "bài",
  },
];
