/** Versioned browser repository keys. Keep existing names to preserve user data. */
export const storageKeys = {
  curriculumTopics: "genai-curriculum-topics-v1",
  curriculumLessons: "genai-curriculum-lessons-v1",
  completedLessons: "genai-curriculum-completed-v1",
  studentGp: "genai-student-gp-v1",
  dailyGp: "genai-student-daily-gp-v1",
  studentGoals: "genai-student-goals-v1",
  studentSchedule: "genai-student-schedule-v1",
  studentSidebarExpanded: "genai-student-sidebar-expanded-v1",
  studentSidebarVisibleV2: "genai-student-sidebar-visible-v2",
  practiceSessionV2: "genai-practice-session-v2",
  practiceSessionsV3: "genai-practice-sessions-v3",
  studentSidebarPinned: "genai-student-sidebar-pinned-v1",
  studentRecentRoutes: "genai-student-recent-routes-v1",
  teacherAssignments: "genai-k12-teacher-assignments-v1",
  adminUsers: "genai-admin-users-v1",
  practiceSession: "genai-practice-session-v1",
  rewardRequests: "genai-reward-requests-v1",
} as const;
