import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Alert, Badge, Button, Card, Field, Icon, Input, Modal, Select, Textarea } from '../components/ui';
import '../index.css';

function DesignPreview() {
  const [subject, setSubject] = useState('math');
  const [modalOpen, setModalOpen] = useState(false);
  const [stage, setStage] = useState('theory');
  const [notice, setNotice] = useState('Các thành phần trên trang này là component thật đang dùng trong ứng dụng.');
  const stages = [{ id: 'theory', label: 'Lý thuyết' }, { id: 'examples', label: 'Ví dụ' }, { id: 'exercises', label: 'Bài tập' }];
  return <main className="mx-auto max-w-content space-y-8 px-4 py-8 sm:px-8">
    <header className="space-y-3"><Badge tone="primary">Thư viện giao diện</Badge><h1 className="text-3xl font-bold text-on-surface">Một hệ thống, mọi màn hình</h1><p className="max-w-3xl text-on-surface-variant">Màu, ô nhập, nút, menu và hộp thoại dùng chung nguồn token. Dùng bàn phím để kiểm tra focus, chọn mục và đóng hộp thoại.</p></header>
    <Alert>{notice}</Alert>
    <div className="grid gap-6 lg:grid-cols-2">
      <Card className="space-y-5 p-5 sm:p-6"><h2 className="text-xl font-bold">Hành động</h2><div className="flex flex-wrap gap-3"><Button onClick={() => setNotice('Đã kiểm tra nút hành động chính.')}><Icon name="save" />Lưu bài học</Button><Button variant="secondary" onClick={() => setNotice('Đã kiểm tra nút phụ.')}><Icon name="visibility" />Xem trước</Button><Button variant="ghost" onClick={() => setNotice('Đã kiểm tra nút ít nổi bật.')}><Icon name="undo" />Quay lại</Button><Button variant="danger" onClick={() => setNotice('Đây là bản xem trước giao diện, không có dữ liệu bị xóa.')}><Icon name="delete" />Xóa</Button></div><div className="flex flex-wrap items-center gap-3"><Button size="sm">Nút nhỏ</Button><Button size="lg">Hành động nổi bật</Button><Button variant="secondary" size="icon" aria-label="Thêm mục"><Icon name="add" /></Button><Button disabled>Đang khóa</Button></div><code className="block overflow-x-auto rounded-control bg-chip p-3 text-sm">{'<Button variant="secondary" size="sm">Xem trước</Button>'}</code></Card>
      <Card className="space-y-5 p-5 sm:p-6"><h2 className="text-xl font-bold">Ô nhập & tìm kiếm</h2><Field label="Tên bài học" hint="Nhãn luôn hiển thị, kể cả khi đã nhập nội dung."><Input placeholder="Nhập tên bài học" /></Field><Field label="Tìm nội dung"><Input type="search" placeholder="Tìm tên bài, chủ đề..." /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Trường bắt buộc" error="Vui lòng nhập tên chủ đề."><Input required placeholder="Tên chủ đề" /></Field><Field label="Chỉ xem"><Input readOnly value="Toán lớp 9" /></Field></div><Field label="Ghi chú"><Textarea rows={2} placeholder="Nội dung mô tả ngắn" /></Field></Card>
      <Card className="space-y-5 p-5 sm:p-6"><h2 className="text-xl font-bold">Menu & lựa chọn</h2><Field label="Môn học" hint="Mũi tên để di chuyển; Enter chọn; Escape đóng; gõ chữ để tìm."><Select value={subject} onChange={event => setSubject(event.target.value)}><option value="math">Toán</option><option value="literature">Ngữ văn</option><option value="english">Tiếng Anh</option><option disabled value="coming">Sắp mở</option><option value="computing">Tin học</option></Select></Field><Field label="Chưa thể thay đổi"><Select disabled value="math"><option value="math">Toán</option></Select></Field><div className="ui-segmented" role="group" aria-label="Phần bài học">{stages.map(item => <Button key={item.id} variant="ghost" size="sm" className="flex-1" aria-pressed={stage === item.id} onClick={() => setStage(item.id)}>{item.label}</Button>)}</div><p className="ui-hint">Đang chọn: {stages.find(item => item.id === stage)?.label}</p><nav aria-label="Điều hướng mẫu" className="space-y-2"><Button variant="ghost" className="ui-nav-item" aria-current="page"><Icon name="menu_book" />Môn học</Button><Button variant="ghost" className="ui-nav-item"><Icon name="insights" />Tiến độ</Button></nav></Card>
      <Card className="space-y-5 p-5 sm:p-6"><h2 className="text-xl font-bold">Trạng thái & hộp thoại</h2><div className="flex flex-wrap gap-2"><Badge>Bản nháp</Badge><Badge tone="success">Đã xuất bản</Badge><Badge tone="warning">Chưa lưu</Badge><Badge tone="danger">Cần sửa</Badge><Badge tone="info">Thông tin</Badge></div><Alert tone="success">Bài học đã được lưu.</Alert><Alert tone="warning">Hoàn thành các trường bắt buộc trước khi xuất bản.</Alert><Alert tone="danger">Không thể lưu. Nội dung đang nhập vẫn được giữ lại.</Alert><Button variant="secondary" onClick={() => setModalOpen(true)}>Mở hộp thoại mẫu</Button><p className="ui-hint">Hộp thoại giữ focus; menu bên trong luôn hiển thị trên bề mặt dialog.</p></Card>
    </div>
    <footer className="border-t border-outline-variant pt-6 text-sm text-on-surface-variant">Nguồn hình thức: <code>src/styles/tokens.css</code> và <code>src/styles/primitives.css</code>. API: <code>src/components/ui</code>. Xem hướng dẫn mở rộng trong <code>DESIGN.md</code>.</footer>
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Cài đặt bài học" description="Thử chọn môn, di chuyển focus và đóng bằng Escape." footer={<><Button variant="ghost" onClick={() => setModalOpen(false)}>Hủy</Button><Button onClick={() => { setModalOpen(false); setNotice('Đã thử lưu cài đặt trong hộp thoại.'); }}>Lưu cài đặt</Button></>}>
      <div className="space-y-5"><Field label="Tên trong hộp thoại"><Input defaultValue="Bài học mẫu" /></Field><Field label="Môn trong hộp thoại"><Select value={subject} onChange={event => setSubject(event.target.value)}><option value="math">Toán</option><option value="literature">Ngữ văn</option><option value="english">Tiếng Anh</option><option value="computing">Tin học</option></Select></Field><Field label="Mô tả"><Textarea rows={4} placeholder="Mục tiêu của bài học" /></Field></div>
    </Modal>
  </main>;
}

createRoot(document.getElementById('root')!).render(<DesignPreview />);
