import type { SVGProps } from "react";
import {
  AccountTree, Add, ArrowBack, ArrowDownward, ArrowForward, ArrowUpward,
  Bolt, Bookmark, Calculate, CalendarMonth, Campaign, Chat, Check, CheckCircle,
  Close, Code, ContentCopy, Dashboard, Delete, Description, Download, Edit,
  EditNote, Explore, FireDepartment, Group, Info, KeyboardArrowDown, Lightbulb,
  LightMode, ListBulleted, Lock, Logout, Menu, MenuBook, Notes, Payments, Person,
  PlayArrow, ProgressActivity, Psychology, Public, Refresh, RestartAlt, Save,
  Schedule, School, Search, Send, Settings, Share, Star, Stars2, Target, ThumbUp,
  Trophy, Tune, Undo, UnknownDocument, Upload, VerifiedUser, Visibility, Warning,
  WorkspacePremium, ArrowOutward,
  type IconComponent,
} from "../icons";
import {
  AlarmClock, Bot, CalendarPlus, CalendarX, CloudCheck, Crosshair, DoorOpen,
  Focus, Headphones, Headset, House, LayoutGrid, Link2, ListVideo, Medal,
  MessageCircleQuestion, Network, PenTool, PlayCircle, ShieldCheck, Trash2,
  Video, MapPin, AlertCircle, Filter, Music2, GraduationCap, Workflow, Pause,
  Languages, FlaskConical, Dna, LockOpen,
} from "../icons/extended";
import { cn } from "./utils";

/**
 * Stable Material-name contract for curriculum data while rendering the same
 * local Material Symbols Rounded SVG language as gen.ai.vn.
 */
export const ICONS: Record<string, IconComponent> = {
  translate: Languages,
  science: FlaskConical,
  biotech: Dna,
  lock_open: LockOpen,
  functions: Calculate,
  pause: Pause,
  add_task: CheckCircle,
  alarm: AlarmClock,
  calendar_add_on: CalendarPlus,
  center_focus_strong: Focus,
  cloud_done: CloudCheck,
  delete_outline: Trash2,
  error: AlertCircle,
  event_busy: CalendarX,
  filter_alt: Filter,
  gesture: PenTool,
  graphic_eq: Music2,
  grid_view: LayoutGrid,
  headphones: Headphones,
  home: House,
  hub: Network,
  link: Link2,
  meeting_room: DoorOpen,
  military_tech: Medal,
  play_lesson: PlayCircle,
  playlist_play: ListVideo,
  question_answer: MessageCircleQuestion,
  room: MapPin,
  shield: ShieldCheck,
  smart_toy: Bot,
  sports_score: GraduationCap,
  support_agent: Headset,
  timeline: Workflow,
  track_changes: Crosshair,
  videocam: Video,
  warning: Warning,
  zoom_out: Focus,

  account_tree: AccountTree,
  add: Add,
  arrow_back: ArrowBack,
  arrow_forward: ArrowForward,
  arrow_upward: ArrowUpward,
  arrow_downward: ArrowDownward,
  assignment: Notes,
  auto_stories: MenuBook,
  bolt: Bolt,
  calculate: Calculate,
  calendar_today: CalendarMonth,
  calendar_month: CalendarMonth,
  card_giftcard: Trophy,
  check: Check,
  check_circle: CheckCircle,
  chevron_right: ArrowForward,
  chevron_left: ArrowBack,
  close: Close,
  content_copy: ContentCopy,
  dashboard: Dashboard,
  delete: Delete,
  description: Description,
  download: Download,
  edit: Edit,
  edit_note: EditNote,
  edit_square: Edit,
  expand_more: KeyboardArrowDown,
  fact_check: CheckCircle,
  favorite: Stars2,
  flag: Target,
  groups: Group,
  history: RestartAlt,
  info: Info,
  insights: Dashboard,
  language: Public,
  library_books: MenuBook,
  lightbulb: Lightbulb,
  local_fire_department: FireDepartment,
  lock: Lock,
  logout: Logout,
  manage_accounts: Person,
  menu: Menu,
  menu_book: MenuBook,
  more_horiz: Notes,
  notifications: Campaign,
  person: Person,
  person_add: Person,
  person_search: Person,
  play_arrow: PlayArrow,
  psychology: Psychology,
  publish: Upload,
  radio_button_unchecked: UnknownDocument,
  refresh: Refresh,
  replay: RestartAlt,
  save: Save,
  savings: Payments,
  school: School,
  search: Search,
  settings: Settings,
  shield_person: VerifiedUser,
  admin_panel_settings: VerifiedUser,
  space_dashboard: Dashboard,
  star: Star,
  task_alt: CheckCircle,
  terminal: Code,
  timer: Schedule,
  trending_up: Dashboard,
  undo: Undo,
  verified: CheckCircle,
  verified_user: VerifiedUser,
  visibility: Visibility,
  visibility_off: Visibility,
  volunteer_activism: Stars2,
  wb_sunny: LightMode,
  emoji_events: Trophy,
  workspace_premium: WorkspacePremium,
  target: Target,
  auto_awesome: Stars2,
  bar_chart: Dashboard,
  bookmark: Bookmark,
  filter_list: Tune,
  schedule: Schedule,
  help: Info,
  chat: Chat,
  accessibility: Person,
  volume_up: Campaign,
  progress_activity: ProgressActivity,
  account_balance_wallet: Payments,
  checklist: ListBulleted,
  folder_open: MenuBook,
  open_in_new: ArrowOutward,
  print: Description,
  quiz: UnknownDocument,
  redeem: Trophy,
  restart_alt: RestartAlt,
  route: Explore,
  search_off: Search,
  stars: Stars2,
  table_chart: Dashboard,
  tips_and_updates: Lightbulb,
  celebration: Stars2,
  send: Send,
  thumb_up: ThumbUp,
  keyboard: Code,
  sports_basketball: Trophy,
  mystery: Trophy,
  install_mobile: Download,
  smartphone: Download,
  wifi_off: Warning,
  cloud_off: Warning,
  share: Share,
};

interface IconProps extends Omit<SVGProps<SVGSVGElement>, "children" | "name"> {
  name?: string;
  children?: string;
  filled?: boolean;
}

export function Icon({ name, children, className, ...props }: IconProps) {
  const iconName = name || children || "";
  const Symbol = ICONS[iconName];
  if (!Symbol) {
    if (import.meta.env.DEV) throw new Error(`Icon chưa khai báo: ${iconName}`);
    return null;
  }
  return <Symbol className={cn("ui-icon", className)} {...props} />;
}
