import type { SVGProps } from "react";
import {
  Accessibility,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Bookmark,
  Brain,
  CalendarDays,
  Calculator,
  ChartNoAxesCombined,
  Check,
  Circle,
  CircleCheck,
  CircleHelp,
  Clock3,
  Copy,
  Download,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ClipboardCheck,
  ClipboardList,
  Eye,
  EyeOff,
  FileText,
  Flag,
  Flame,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  History,
  Info,
  LayoutDashboard,
  LibraryBig,
  Lightbulb,
  ListFilter,
  LoaderCircle,
  LockKeyhole,
  LogOut,
  Menu,
  MessageCircle,
  MoreHorizontal,
  Network,
  Pencil,
  PiggyBank,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Settings,
  Share2,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Target,
  Terminal,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  Upload,
  UserCog,
  UserPlus,
  UserRound,
  UserRoundSearch,
  Users,
  Volume2,
  WifiOff,
  X,
  Zap,
  Wallet,
  ListChecks,
  FolderOpen,
  ExternalLink,
  Printer,
  FileQuestion,
  Route,
  SearchX,
  Table2,
  PartyPopper,
  Send,
  ThumbsUp,
  Keyboard,
  Dribbble,
  type LucideIcon,
} from "lucide-react";
import { cn } from "./utils";

// Existing curriculum records use Material names. Keep that stable data contract
// while rendering local, tree-shaken SVGs instead of depending on a font request.
const ICONS: Record<string, LucideIcon> = {
  account_tree: Network,
  add: Plus,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  assignment: ClipboardList,
  auto_stories: BookOpen,
  bolt: Zap,
  calculate: Calculator,
  calendar_today: CalendarDays,
  calendar_month: CalendarDays,
  card_giftcard: Gift,
  check: Check,
  check_circle: CircleCheck,
  chevron_right: ChevronRight,
  chevron_left: ChevronLeft,
  close: X,
  content_copy: Copy,
  dashboard: LayoutDashboard,
  delete: Trash2,
  description: FileText,
  download: Download,
  edit: Pencil,
  edit_note: Pencil,
  edit_square: Pencil,
  expand_more: ChevronDown,
  fact_check: ClipboardCheck,
  favorite: Heart,
  flag: Flag,
  groups: Users,
  history: History,
  info: Info,
  insights: ChartNoAxesCombined,
  language: Globe,
  library_books: LibraryBig,
  lightbulb: Lightbulb,
  local_fire_department: Flame,
  lock: LockKeyhole,
  logout: LogOut,
  manage_accounts: UserCog,
  menu: Menu,
  menu_book: BookOpen,
  more_horiz: MoreHorizontal,
  notifications: Bell,
  person: UserRound,
  person_add: UserPlus,
  person_search: UserRoundSearch,
  play_arrow: Play,
  psychology: Brain,
  publish: Upload,
  radio_button_unchecked: Circle,
  refresh: RefreshCw,
  replay: RotateCcw,
  save: Save,
  savings: PiggyBank,
  school: GraduationCap,
  search: Search,
  settings: Settings,
  shield_person: ShieldCheck,
  admin_panel_settings: ShieldCheck,
  space_dashboard: LayoutDashboard,
  star: Star,
  task_alt: CircleCheck,
  terminal: Terminal,
  timer: Timer,
  trending_up: TrendingUp,
  undo: RotateCcw,
  verified: CircleCheck,
  verified_user: ShieldCheck,
  visibility: Eye,
  visibility_off: EyeOff,
  volunteer_activism: Heart,
  wb_sunny: Sun,
  emoji_events: Trophy,
  workspace_premium: Award,
  target: Target,
  auto_awesome: Sparkles,
  bar_chart: BarChart3,
  bookmark: Bookmark,
  filter_list: ListFilter,
  schedule: Clock3,
  help: CircleHelp,
  chat: MessageCircle,
  accessibility: Accessibility,
  volume_up: Volume2,
  progress_activity: LoaderCircle,
  account_balance_wallet: Wallet,
  checklist: ListChecks,
  folder_open: FolderOpen,
  open_in_new: ExternalLink,
  print: Printer,
  quiz: FileQuestion,
  redeem: Gift,
  restart_alt: RotateCcw,
  route: Route,
  search_off: SearchX,
  stars: Sparkles,
  table_chart: Table2,
  tips_and_updates: Lightbulb,
  celebration: PartyPopper,
  send: Send,
  thumb_up: ThumbsUp,
  keyboard: Keyboard,
  sports_basketball: Dribbble,
  mystery: Gift,
  install_mobile: Smartphone,
  smartphone: Smartphone,
  wifi_off: WifiOff,
  cloud_off: WifiOff,
  share: Share2,
};

interface IconProps extends Omit<SVGProps<SVGSVGElement>, "children" | "name"> {
  name?: string;
  children?: string;
}

export function Icon({ name, children, className, ...props }: IconProps) {
  const Symbol = ICONS[name || children || ""] || CircleHelp;
  return (
    <Symbol
      aria-hidden={props["aria-label"] ? undefined : true}
      role={props["aria-label"] ? "img" : undefined}
      className={cn("ui-icon", className)}
      {...props}
    />
  );
}
